"""event max team size

Revision ID: 7ba503b631f7
Revises: 9c33c1526463
Create Date: 2026-09-26 15:54:45.586507

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ba503b631f7"
down_revision: Union[str, Sequence[str], None] = "9c33c1526463"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("max_team_size", sa.Integer(), server_default="4", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_column("max_team_size")

    # ### end Alembic commands ###
