"""flag reason, prize awards, token scope and expiry

Revision ID: 74da086d108b
Revises: 7ba503b631f7
Create Date: 2026-09-27 01:58:36.593291

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74da086d108b"
down_revision: Union[str, Sequence[str], None] = "7ba503b631f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("scope", sa.String(length=10), server_default="write", nullable=False)
        )
        batch_op.add_column(sa.Column("expires_at", sa.DateTime(), nullable=True))

    with op.batch_alter_table("prizes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("project_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_prizes_project_id_projects", "projects", ["project_id"], ["id"], ondelete="SET NULL"
        )

    with op.batch_alter_table("votes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("flag_reason", sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("votes", schema=None) as batch_op:
        batch_op.drop_column("flag_reason")

    with op.batch_alter_table("prizes", schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint("fk_prizes_project_id_projects", type_="foreignkey")
        batch_op.drop_column("project_id")

    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.drop_column("expires_at")
        batch_op.drop_column("scope")

    # ### end Alembic commands ###
