"""initial schema

Revision ID: 9c33c1526463
Revises:
Create Date: 2026-09-26 15:48:05.648512

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c33c1526463"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instance_settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_public_id"), ["public_id"], unique=True)

    op.create_table(
        "api_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("prefix", sa.String(length=12), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("submissions_open_at", sa.DateTime(), nullable=True),
        sa.Column("submissions_close_at", sa.DateTime(), nullable=True),
        sa.Column("judging_opened_at", sa.DateTime(), nullable=True),
        sa.Column("judging_closed_at", sa.DateTime(), nullable=True),
        sa.Column("voting_open_at", sa.DateTime(), nullable=True),
        sa.Column("voting_close_at", sa.DateTime(), nullable=True),
        sa.Column("results_published_at", sa.DateTime(), nullable=True),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column(
            "voting_mode",
            sa.Enum("link", "email", "account", name="votingmode", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("quadratic_enabled", sa.Boolean(), nullable=False),
        sa.Column("voting_credits", sa.Integer(), nullable=False),
        sa.Column("comments_enabled", sa.Boolean(), nullable=False),
        sa.Column("reviews_per_project", sa.Integer(), nullable=False),
        sa.Column(
            "normalization_method",
            sa.Enum("none", "zscore", name="normalizationmethod", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "published_ranking",
            sa.Enum("raw", "normalized", name="rankingbasis", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_public_id"), ["public_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_events_slug"), ["slug"], unique=True)

    op.create_table(
        "sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("row_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_event_id"), ["event_id"], unique=False)

    op.create_table(
        "event_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("participant", "judge", "organizer", name="role", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "user_id", name="uq_event_roles_event_user"),
    )
    with op.batch_alter_table("event_roles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_event_roles_event_id"), ["event_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_event_roles_user_id"), ["user_id"], unique=False)

    op.create_table(
        "judge_invites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("track_public_ids", sa.JSON(), nullable=False),
        sa.Column("invited_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("accepted_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["accepted_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["invited_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("judge_invites", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_judge_invites_event_id"), ["event_id"], unique=False)

    op.create_table(
        "rubric_criteria",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("min_score", sa.Integer(), nullable=False),
        sa.Column("max_score", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "key", name="uq_rubric_event_key"),
    )
    with op.batch_alter_table("rubric_criteria", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rubric_criteria_event_id"), ["event_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_rubric_criteria_public_id"), ["public_id"], unique=True
        )

    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("invite_code", sa.String(length=40), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_teams_event_id"), ["event_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_teams_invite_code"), ["invite_code"], unique=True)
        batch_op.create_index(batch_op.f("ix_teams_public_id"), ["public_id"], unique=True)

    op.create_table(
        "tracks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "name", name="uq_tracks_event_name"),
    )
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tracks_event_id"), ["event_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tracks_public_id"), ["public_id"], unique=True)

    op.create_table(
        "voter_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("issued_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code_hash"),
    )
    with op.batch_alter_table("voter_codes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_voter_codes_event_id"), ["event_id"], unique=False)

    op.create_table(
        "voter_ledger",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("voter_key", sa.String(length=128), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("email_hash", sa.String(length=64), nullable=True),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("credits_spent", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "voter_key", name="uq_voter_ledger_event_key"),
    )
    with op.batch_alter_table("voter_ledger", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_voter_ledger_event_id"), ["event_id"], unique=False)

    op.create_table(
        "webhooks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("secret", sa.String(length=128), nullable=False),
        sa.Column("event_types", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("webhooks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_webhooks_event_id"), ["event_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_webhooks_public_id"), ["public_id"], unique=True)

    op.create_table(
        "certificates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "participation",
                "judge",
                "winner",
                name="certificatekind",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("serial", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("signature", sa.Text(), nullable=False),
        sa.Column("issued_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("certificates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_certificates_event_id"), ["event_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_certificates_serial"), ["serial"], unique=True)

    op.create_table(
        "judge_tracks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "user_id", "track_id", name="uq_judge_tracks"),
    )
    with op.batch_alter_table("judge_tracks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_judge_tracks_event_id"), ["event_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_judge_tracks_track_id"), ["track_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_judge_tracks_user_id"), ["user_id"], unique=False)

    op.create_table(
        "prizes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("amount_text", sa.String(length=60), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("prizes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_prizes_event_id"), ["event_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_prizes_public_id"), ["public_id"], unique=True)

    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=140), nullable=False),
        sa.Column("summary", sa.String(length=280), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("repo_url", sa.String(length=500), nullable=False),
        sa.Column("demo_url", sa.String(length=500), nullable=False),
        sa.Column("video_url", sa.String(length=500), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "submitted",
                "withdrawn",
                name="projectstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(), nullable=True),
        sa.Column("unlocked_until", sa.DateTime(), nullable=True),
        sa.Column("duplicate_of_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["duplicate_of_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_event_id"), ["event_id"], unique=False)
        batch_op.create_index("ix_projects_event_status", ["event_id", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_projects_public_id"), ["public_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_projects_team_id"), ["team_id"], unique=False)

    op.create_table(
        "team_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("lead", "member", name="memberrole", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "user_id", name="uq_team_members_team_user"),
    )
    with op.batch_alter_table("team_members", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_team_members_team_id"), ["team_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_team_members_user_id"), ["user_id"], unique=False)

    op.create_table(
        "webhook_deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("webhook_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "delivered",
                "failed",
                name="deliverystatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_status_code", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["webhook_id"], ["webhooks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("webhook_deliveries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_webhook_deliveries_next_attempt_at"), ["next_attempt_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_webhook_deliveries_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_webhook_deliveries_webhook_id"), ["webhook_id"], unique=False
        )

    op.create_table(
        "assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("judge_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_progress",
                "done",
                name="assignmentstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "method",
            sa.Enum(
                "manual", "auto", "imported", name="assignmentmethod", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("assigned_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["assigned_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["judge_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("judge_id", "project_id", name="uq_assignments_judge_project"),
    )
    with op.batch_alter_table("assignments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_assignments_event_id"), ["event_id"], unique=False)
        batch_op.create_index("ix_assignments_event_judge", ["event_id", "judge_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_assignments_judge_id"), ["judge_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_assignments_project_id"), ["project_id"], unique=False)

    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("hidden_at", sa.DateTime(), nullable=True),
        sa.Column("hidden_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["hidden_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_comments_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_comments_public_id"), ["public_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_comments_user_id"), ["user_id"], unique=False)

    op.create_table(
        "pairwise_comparisons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("judge_id", sa.Integer(), nullable=False),
        sa.Column("project_a_id", sa.Integer(), nullable=False),
        sa.Column("project_b_id", sa.Integer(), nullable=False),
        sa.Column("winner_id", sa.Integer(), nullable=True),
        sa.Column("skip_reason", sa.String(length=80), nullable=True),
        sa.Column(
            "source",
            sa.Enum("judge", "derived", name="comparisonsource", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["judge_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_a_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_b_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["winner_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pairwise_comparisons", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pairwise_comparisons_event_id"), ["event_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_pairwise_comparisons_judge_id"), ["judge_id"], unique=False
        )
        batch_op.create_index("ix_pairwise_event_judge", ["event_id", "judge_id"], unique=False)

    op.create_table(
        "votes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("voter_key", sa.String(length=128), nullable=False),
        sa.Column("voter_user_id", sa.Integer(), nullable=True),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("ua_hash", sa.String(length=64), nullable=True),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("voided_at", sa.DateTime(), nullable=True),
        sa.Column("void_reason", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["voter_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "event_id", "project_id", "voter_key", name="uq_votes_event_project_voter"
        ),
    )
    with op.batch_alter_table("votes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_votes_event_id"), ["event_id"], unique=False)
        batch_op.create_index("ix_votes_event_project", ["event_id", "project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_votes_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_votes_voter_key"), ["voter_key"], unique=False)

    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("assignment_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("judge_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "submitted", name="reviewstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["assignment_id"], ["assignments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["judge_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assignment_id"),
        sa.UniqueConstraint("judge_id", "project_id", name="uq_reviews_judge_project"),
    )
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reviews_event_id"), ["event_id"], unique=False)
        batch_op.create_index("ix_reviews_event_judge", ["event_id", "judge_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_reviews_judge_id"), ["judge_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_reviews_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_reviews_public_id"), ["public_id"], unique=True)

    op.create_table(
        "score_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("criterion_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["criterion_id"], ["rubric_criteria.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["review_id"], ["reviews.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("review_id", "criterion_id", name="uq_score_items_review_criterion"),
    )
    with op.batch_alter_table("score_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_score_items_criterion_id"), ["criterion_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_score_items_review_id"), ["review_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("score_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_score_items_review_id"))
        batch_op.drop_index(batch_op.f("ix_score_items_criterion_id"))

    op.drop_table("score_items")
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reviews_public_id"))
        batch_op.drop_index(batch_op.f("ix_reviews_project_id"))
        batch_op.drop_index(batch_op.f("ix_reviews_judge_id"))
        batch_op.drop_index("ix_reviews_event_judge")
        batch_op.drop_index(batch_op.f("ix_reviews_event_id"))

    op.drop_table("reviews")
    with op.batch_alter_table("votes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_votes_voter_key"))
        batch_op.drop_index(batch_op.f("ix_votes_project_id"))
        batch_op.drop_index("ix_votes_event_project")
        batch_op.drop_index(batch_op.f("ix_votes_event_id"))

    op.drop_table("votes")
    with op.batch_alter_table("pairwise_comparisons", schema=None) as batch_op:
        batch_op.drop_index("ix_pairwise_event_judge")
        batch_op.drop_index(batch_op.f("ix_pairwise_comparisons_judge_id"))
        batch_op.drop_index(batch_op.f("ix_pairwise_comparisons_event_id"))

    op.drop_table("pairwise_comparisons")
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comments_user_id"))
        batch_op.drop_index(batch_op.f("ix_comments_public_id"))
        batch_op.drop_index(batch_op.f("ix_comments_project_id"))

    op.drop_table("comments")
    with op.batch_alter_table("assignments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assignments_project_id"))
        batch_op.drop_index(batch_op.f("ix_assignments_judge_id"))
        batch_op.drop_index("ix_assignments_event_judge")
        batch_op.drop_index(batch_op.f("ix_assignments_event_id"))

    op.drop_table("assignments")
    with op.batch_alter_table("webhook_deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_webhook_deliveries_webhook_id"))
        batch_op.drop_index(batch_op.f("ix_webhook_deliveries_status"))
        batch_op.drop_index(batch_op.f("ix_webhook_deliveries_next_attempt_at"))

    op.drop_table("webhook_deliveries")
    with op.batch_alter_table("team_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_team_members_user_id"))
        batch_op.drop_index(batch_op.f("ix_team_members_team_id"))

    op.drop_table("team_members")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_team_id"))
        batch_op.drop_index(batch_op.f("ix_projects_public_id"))
        batch_op.drop_index("ix_projects_event_status")
        batch_op.drop_index(batch_op.f("ix_projects_event_id"))

    op.drop_table("projects")
    with op.batch_alter_table("prizes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prizes_public_id"))
        batch_op.drop_index(batch_op.f("ix_prizes_event_id"))

    op.drop_table("prizes")
    with op.batch_alter_table("judge_tracks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_judge_tracks_user_id"))
        batch_op.drop_index(batch_op.f("ix_judge_tracks_track_id"))
        batch_op.drop_index(batch_op.f("ix_judge_tracks_event_id"))

    op.drop_table("judge_tracks")
    with op.batch_alter_table("certificates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_certificates_serial"))
        batch_op.drop_index(batch_op.f("ix_certificates_event_id"))

    op.drop_table("certificates")
    with op.batch_alter_table("webhooks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_webhooks_public_id"))
        batch_op.drop_index(batch_op.f("ix_webhooks_event_id"))

    op.drop_table("webhooks")
    with op.batch_alter_table("voter_ledger", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_voter_ledger_event_id"))

    op.drop_table("voter_ledger")
    with op.batch_alter_table("voter_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_voter_codes_event_id"))

    op.drop_table("voter_codes")
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracks_public_id"))
        batch_op.drop_index(batch_op.f("ix_tracks_event_id"))

    op.drop_table("tracks")
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_teams_public_id"))
        batch_op.drop_index(batch_op.f("ix_teams_invite_code"))
        batch_op.drop_index(batch_op.f("ix_teams_event_id"))

    op.drop_table("teams")
    with op.batch_alter_table("rubric_criteria", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rubric_criteria_public_id"))
        batch_op.drop_index(batch_op.f("ix_rubric_criteria_event_id"))

    op.drop_table("rubric_criteria")
    with op.batch_alter_table("judge_invites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_judge_invites_event_id"))

    op.drop_table("judge_invites")
    with op.batch_alter_table("event_roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_roles_user_id"))
        batch_op.drop_index(batch_op.f("ix_event_roles_event_id"))

    op.drop_table("event_roles")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_event_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_action"))

    op.drop_table("audit_log")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))

    op.drop_table("sessions")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_slug"))
        batch_op.drop_index(batch_op.f("ix_events_public_id"))

    op.drop_table("events")
    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_tokens_user_id"))

    op.drop_table("api_tokens")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_public_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("instance_settings")
    # ### end Alembic commands ###
